import localFont from "next/font/local";
import "./globals.css";
import {Sour_Gummy} from "next/font/google"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customFont = Sour_Gummy({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={customFont.className}
      >
        {children}
      </body>
    </html>
  );
}
